run:
  timeout: 5m
  issues-exit-code: 0 # Initial non-blocking

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - revive
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/maakie-brainlab

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
