package prbodyfix

import (
	"fmt"
	"strings"
)

const (
	SentinelPrefix = "PR_BODY_TEMPLATE_v1:"
	EvidenceHeader = "## Evidence"
)

// Normalize computes the desired PR body based on current content and inputs.
// It is a pure function: same inputs -> same output.
func Normalize(currentBody, templateBody, headSHA, runURL string) string {
	// 1. Strip sentinel lines from current body
	cleaned := stripSentinel(currentBody)

	// 2. If empty, fallback to template
	if strings.TrimSpace(cleaned) == "" {
		// usage of template: also strip sentinel from template
		tmplClean := stripSentinel(templateBody)
		if strings.TrimSpace(tmplClean) != "" {
			cleaned = tmplClean
		} else {
			// 3. If template is also empty/missing, use minimal body
			cleaned = fmt.Sprintf("Minimal Body\n\nHeadSHA: %s\nRun: %s", headSHA, runURL)
		}
	}

	// 4. Ensure Evidence section exists (if we have a structured body)
	// If it's the minimal body we constructed above, it doesn't strictly need "## Evidence"
	// based on the S19-01 spec, but S19-02 spec says "CI側の Evidence は 不変情報だけ".
	// Let's stick to the S19-01 pattern where evidence is injected if missing.
	// However, if we just used the minimal body, maybe we don't need to inject a second evidence section?
	// The minimal body example in Plan doesn't use ## Evidence header explicitly in the fallback string,
	// but let's be consistent.

	// Actually, Plan says:
	// - ensure evidence section exists
	// - ensure trailing newline exactly 1

	// Let's check if we need to inject Evidence header.
	if !strings.Contains(cleaned, EvidenceHeader) {
		// If it's a "Minimal Body" generated by us, maybe we should format it nicely?
		// But if it's user content without evidence, append it.
		if strings.TrimSpace(cleaned) != "" {
			cleaned += "\n\n" + EvidenceHeader + "\n"
		}
	}

	// We are NOT injecting dynamic evidence (bundle path etc) in CI,
	// only immutable info if we are strictly following "CI側の Evidence は 不変情報だけ".
	// But wait, the previous implementation injected "HeadSHA" and "Run".
	// The Plan says: "Evidence は 不変情報だけ ... HeadSHA ... Run".
	// So we should probably ensure these lines exist under Evidence?
	// The Plan's pseudocode for `Normalize` implies:
	// "desired = Normalize(currentBody, template, headSHA, runURL)"
	// But it doesn't explicitly say "Inject these lines".
	// However, usually CI ensures these lines are present.
	// Let's look at S19-01 implementation: it injects them.
	// In S19-02, `cmd/prbodyfix` is the CI insurance. So it SHOULD inject them if missing.

	// Let's implement injection of immutable evidence.
	cleaned = ensureEvidenceLines(cleaned, headSHA, runURL)

	// 5. Ensure trailing newline
	return ensureTrailingNewline(cleaned)
}

func stripSentinel(s string) string {
	lines := strings.Split(s, "\n")
	var keep []string
	for _, l := range lines {
		// TrimLeft to ignore indentation, but sentinel is usually at start
		// Plan says: "sentinel行除去は TrimSpace 禁止（TrimLeft は可：indent吸収）"
		// "empty判定だけ TrimSpace"
		trimmed := strings.TrimLeft(l, " \t")
		if strings.HasPrefix(trimmed, SentinelPrefix) {
			continue
		}
		keep = append(keep, l)
	}
	return strings.Join(keep, "\n")
}

func ensureEvidenceLines(body, headSHA, runURL string) string {
	// Simple approach: Check if lines exist, if not append to Evidence section.
	// This is a bit complex to do consistently with pure string manipulation if user edited it.
	// But for "CI Insurance", valid evidence is better than no evidence.

	// If body doesn't have evidence section, we added it.
	// Now let's try to append lines if they are missing.

	linesToAdd := []string{}

	shaLine := fmt.Sprintf("- HeadSHA: `%s`", headSHA)
	if !strings.Contains(body, shaLine) {
		linesToAdd = append(linesToAdd, shaLine)
	}

	runLine := fmt.Sprintf("- Run: %s", runURL)
	// Run URL might change on every run?
	// If so, `desired != current` will always be true, breaking idempotency if we blindly update.
	// Plan says: "Run（Actions run URL）... 更新は desired != current のときだけ（冪等）"
	// If Run URL changes every time, we will always update.
	// UNLESS we check if *any* Run URL is present?
	// Or maybe we only inject if NO Run URL is present?
	// "Updates should be idempotent". If we run twice in same workflow job, URL is same.
	// If we run on a Re-run, URL changes -> Update is expected.
	// So exact match is fine.

	if !strings.Contains(body, runLine) {
		linesToAdd = append(linesToAdd, runLine)
	}

	if len(linesToAdd) == 0 {
		return body
	}

	// Insert after Evidence Header
	// We iterate lines to find headers.
	lines := strings.Split(body, "\n")
	insertIdx := -1
	for i, l := range lines {
		if strings.TrimSpace(l) == EvidenceHeader {
			insertIdx = i + 1 // insert after
			break
		}
	}

	if insertIdx == -1 {
		// Should not happen as we ensured header, but fallback append
		return body + "\n" + strings.Join(linesToAdd, "\n")
	}

	// Insert
	newLines := append(lines[:insertIdx], append(linesToAdd, lines[insertIdx:]...)...)
	return strings.Join(newLines, "\n")
}

func ensureTrailingNewline(s string) string {
	if s == "" {
		return "\n"
	}
	if strings.HasSuffix(s, "\n") {
		// Prevent double/triple newlines?
		// Plan: "EnsureTrailingNewline は 1回だけ"
		// If it already implies one, we are good.
		// If multiple, maybe trim?
		// "Ensure trailing newline exactly 1" -> usually means trim right and add one.
		return strings.TrimRight(s, "\n") + "\n"
	}
	return s + "\n"
}
