#!/usr/bin/env bash

PHASE_ID="$1"
TITLE="$2"

if [ -z "$PHASE_ID" ] || [ -z "$TITLE" ]; then
  echo "ERROR: usage: ops/new_ops_phase.sh <PHASE_ID> <TITLE>"
  echo "ERROR: example: ops/new_ops_phase.sh S18-02 \"Phase Title\""
  exit 2
fi

ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -z "$ROOT" ]; then
  echo "ERROR: not a git repo (cannot resolve repo root)"
  exit 3
fi

DOCS_DIR="${ROOT}/docs/ops"
TPL_PLAN="${DOCS_DIR}/meta/DETERMINISTIC_PLAN_TEMPLATE.md"
TPL_TASK="${DOCS_DIR}/meta/DETERMINISTIC_TASK_TEMPLATE.md"

if [ ! -f "$TPL_PLAN" ]; then
  echo "ERROR: missing template: ${TPL_PLAN}"
  exit 4
fi
if [ ! -f "$TPL_TASK" ]; then
  echo "ERROR: missing template: ${TPL_TASK}"
  exit 4
fi

OUT_PLAN="${DOCS_DIR}/${PHASE_ID}_PLAN.md"
OUT_TASK="${DOCS_DIR}/${PHASE_ID}_TASK.md"

write_one () {
  KIND="$1"      # PLAN or TASK
  TPL="$2"
  OUT="$3"

  if [ -f "$OUT" ]; then
    echo "SKIP: exists ${OUT}"
    return 0
  fi

  TMP="${OUT}.tmp.$$"
  HEADER="# ${PHASE_ID} ${KIND} — ${TITLE}"

  {
    echo "${HEADER}"
    echo
    echo "<!-- generated by ops/new_ops_phase.sh | template=$(basename "$TPL") -->"
    echo
    awk 'NR==1 && $0 ~ /^# / {next} {print}' "$TPL"
  } > "$TMP"

  if [ ! -f "$TMP" ]; then
    echo "ERROR: failed to write temp file: ${TMP}"
    exit 5
  fi

  mv "$TMP" "$OUT"
  echo "OK: wrote ${OUT}"
}

write_one "PLAN" "$TPL_PLAN" "$OUT_PLAN"
write_one "TASK" "$TPL_TASK" "$OUT_TASK"
