#!/bin/bash
set -euo pipefail

# S5-02 Review Pack Generator
# Usage: bash ops/s5_pack.sh

# -----------------------------------------------------------------------------
# 1. Pre-flight Checks
# -----------------------------------------------------------------------------

# Check for clean git working tree
if [ -n "$(git status --porcelain)" ]; then
    echo "[FAIL] Git working tree is dirty. Please commit or stash changes."
    exit 1
fi

# Check for required files
if [ ! -f "docs/rules" ] && [ ! -d "docs/rules" ]; then # docs/rules can be a dir or file depending on repo structure, prompt says "docs/rules exists"
    echo "[FAIL] docs/rules not found."
    exit 1
fi

if [ ! -f "ops/gate1.sh" ]; then
    echo "[FAIL] ops/gate1.sh not found."
    exit 1
fi

# -----------------------------------------------------------------------------
# 2. Setup & Execution
# -----------------------------------------------------------------------------

# Generate Timestamp (UTC)
TS=$(date -u +"%Y%m%dT%H%M%SZ")
PACK_DIR=".local/reviewpack_artifacts"
mkdir -p "$PACK_DIR"

GATE1_LOG="$PACK_DIR/gate1.$TS.log"

echo "[S5] Running Gate-1..."
if ! make gate1 > "$GATE1_LOG" 2>&1; then
    echo "[FAIL] Gate-1 failed. See log: $GATE1_LOG"
    exit 1
fi

# Extract Target result
# Look for "Target result: eval/results/..." in the log
RESULT_SRC=$(grep "Target result:" "$GATE1_LOG" | awk '{print $3}')

if [ -z "$RESULT_SRC" ]; then
    echo "[FAIL] Could not extract Target result from Gate-1 log."
    # Fallback: try to find the latest jsonl file created
    # RESULT_SRC=$(ls -t eval/results/*.jsonl | head -n 1) # Avoid if possible per requirements
    exit 1
fi

echo "[S5] Target result: $RESULT_SRC"

# -----------------------------------------------------------------------------
# 3. Staging & Packing
# -----------------------------------------------------------------------------

STAGE_DIR="/tmp/s5_stage_$TS"
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR/ops" "$STAGE_DIR/eval/results" "$STAGE_DIR/docs"

# Copy files
# Handle docs/rules being a file or directory
cp -r docs/rules "$STAGE_DIR/docs/"
cp ops/gate1.sh "$STAGE_DIR/ops/"
cp "$RESULT_SRC" "$STAGE_DIR/eval/results/latest.jsonl"

if [ -f "VERIFY" ]; then
    cp VERIFY "$STAGE_DIR/"
fi

# Generate MANIFEST.txt
MANIFEST="$STAGE_DIR/MANIFEST.txt"
HEAD_HASH=$(git rev-parse HEAD)

{
    echo "ts=$TS"
    echo "head=$HEAD_HASH"
    echo "result_src=$RESULT_SRC"
    echo "--- included files ---"
    (cd "$STAGE_DIR" && find . -type f ! -name "MANIFEST.txt" | sort | sed 's|^\./||')
    echo "--- sha256 checksums ---"
    (cd "$STAGE_DIR" && find . -type f ! -name "MANIFEST.txt" | sort | xargs sha256sum)
} > "$MANIFEST"

# Create tar.gz
PACK_NAME="review_pack_$TS.tar.gz"
PACK_PATH="$PACK_DIR/$PACK_NAME"

(cd "$STAGE_DIR" && COPYFILE_DISABLE=1 tar -czf - .) > "$PACK_PATH"

# Calculate pack SHA256
PACK_SHA=$(sha256sum "$PACK_PATH" | awk '{print $1}')

# Cleanup stage
rm -rf "$STAGE_DIR"

# -----------------------------------------------------------------------------
# 4. Finalize
# -----------------------------------------------------------------------------

# Update SUBMIT_HISTORY.sha256
HISTORY_FILE="SUBMIT_HISTORY.sha256"
# Format: <sha>  <packname>  head=<head>  ts=<TS>  result_src=<RESULT_SRC>
echo "$PACK_SHA  $PACK_NAME  head=$HEAD_HASH  ts=$TS  result_src=$RESULT_SRC" >> "$HISTORY_FILE"

echo ""
echo "=== S5 Review Pack Created ==="
echo "HEAD: $HEAD_HASH"
echo "PACK: $PACK_PATH"
echo "SHA:  $PACK_SHA"
echo "LOG:  $GATE1_LOG"
# Check for optional PRVerify log (not implemented in this script but mentioned in reqs "if exists")
# Assuming it might be generated by something else or we just mention if we found one.
# For now, just listing what we have.

exit 0
